# Generated by Django 6.0.6 on 2026-06-19 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='founditems',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='founditems',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_items_images/'),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='time',
            field=models.TimeField(),
        ),
    ]
