# Generated by Django 6.0.6 on 2026-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0002_founditems_category_founditems_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='handover_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('POLICE', 'Police'), ('INSTITUTION', 'Institution')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='founditems',
            name='wants_reward',
            field=models.BooleanField(default=False),
        ),
    ]
