"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend_drf/.env (for local development).
# In production (Hugging Face Spaces), set these as Space "secrets" instead.
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default='False'):
    return os.environ.get(name, default).strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-2#3-g0l-cup%#7zweh=7#77fp=(%j%37=0g8(xvn&f6dag*n)b',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', 'True')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    'ALLOWED_HOSTS', 'localhost,127.0.0.1'
).split(',') if h.strip()]

# ── CORS (Cross-Origin Resource Sharing) ────────────────────────────────────
# Locally the Vite dev proxy makes API calls same-origin, so CORS isn't hit.
# In production the frontend (Vercel) and backend (Hugging Face Spaces) are on
# different origins, so the deployed frontend URL must be allowed here.
# Set the env var in production, e.g.:
#   CORS_ALLOWED_ORIGINS=https://your-app.vercel.app
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True

# Needed for Django admin / CSRF-protected POSTs from the deployed frontend host.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get(
    'CSRF_TRUSTED_ORIGINS', ''
).split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'user_accounts',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'lost_items',
    'found_items',
    'matching',
    'notifications',
    'rewards',
    'escalations',
    'claims',
    'chat',
    'validation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (Django admin CSS/JS) directly from the
    # app in production — no separate web server needed. Must sit right after
    # SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',   # must be above CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def env_str(name, default=''):
    """Read an env var and strip stray whitespace/tabs/newlines that can sneak
    in via copy-paste into a secrets manager (e.g. a leading tab in a DB name)."""
    return os.environ.get(name, default).strip()


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env_str('POSTGRES_DB', 'lost_found_ai'),
        'USER': env_str('POSTGRES_USER', 'postgres'),
        'PASSWORD': env_str('POSTGRES_PASSWORD', 'postgres'),
        'HOST': env_str('POSTGRES_HOST', 'localhost'),
        'PORT': env_str('POSTGRES_PORT', '5432'),
        # Managed Postgres (e.g. Supabase) requires SSL. Set POSTGRES_SSLMODE=require.
        'OPTIONS': ({'sslmode': env_str('POSTGRES_SSLMODE')}
                    if env_str('POSTGRES_SSLMODE') else {}),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic gathers admin/DRF static files here; WhiteNoise serves them.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Uploaded media (item images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Media storage: Supabase Storage (S3-compatible) when configured ──────────
# Hugging Face Spaces has an EPHEMERAL filesystem, so uploaded images would be
# lost on every restart. When SUPABASE_S3_ENDPOINT is set, store media in a
# Supabase Storage bucket instead (persistent + served from a public URL).
# Leave it unset locally to keep using the local `media/` folder.
SUPABASE_S3_ENDPOINT = env_str('SUPABASE_S3_ENDPOINT')  # https://<ref>.supabase.co/storage/v1/s3
SUPABASE_S3_ACCESS_KEY = env_str('SUPABASE_S3_ACCESS_KEY')
SUPABASE_S3_SECRET_KEY = env_str('SUPABASE_S3_SECRET_KEY')
# Only switch to Supabase Storage once the endpoint AND keys are all present —
# otherwise keep local disk so dev isn't broken before the keys are created.
if SUPABASE_S3_ENDPOINT and SUPABASE_S3_ACCESS_KEY and SUPABASE_S3_SECRET_KEY:
    _bucket = env_str('SUPABASE_STORAGE_BUCKET', 'media')
    _public_host = SUPABASE_S3_ENDPOINT.split('://', 1)[-1].replace('/storage/v1/s3', '')
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'endpoint_url': SUPABASE_S3_ENDPOINT,
            'access_key': SUPABASE_S3_ACCESS_KEY,
            'secret_key': SUPABASE_S3_SECRET_KEY,
            'bucket_name': _bucket,
            'region_name': env_str('SUPABASE_S3_REGION', 'ap-northeast-1'),
            'addressing_style': 'path',       # Supabase requires path-style URLs
            'signature_version': 's3v4',
            'file_overwrite': False,
            'default_acl': None,              # Supabase has no per-object ACLs
            'querystring_auth': False,        # public bucket -> clean, unsigned URLs
            # Serve objects from the public object URL, not the private S3 API path.
            'custom_domain': f'{_public_host}/storage/v1/object/public/{_bucket}',
            'url_protocol': 'https:',
        },
    }

# ── Production hardening (only active when DEBUG=False) ──────────────────────
# Hugging Face Spaces terminates TLS at its proxy and forwards over HTTP with
# this header, so Django knows the original request was HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Secure-by-default: every endpoint requires JWT auth unless it opts out
    # with permission_classes = [AllowAny] (register/login/refresh do).
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # OpenAPI schema generation for Swagger UI / ReDoc.
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Lost & Found AI API',
    'DESCRIPTION': 'Auth (JWT), lost/found reports, AI matching, claims, chat, '
                   'rewards, notifications, and admin endpoints.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Docs/schema endpoints are public even though the API defaults to auth.
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=20),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# Razorpay (UPI / card checkout). Set these to your TEST keys to go live:
#   setx RAZORPAY_KEY_ID  rzp_test_xxx   (then restart the shell)
#   setx RAZORPAY_KEY_SECRET  yyy
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')