# Generated by Django 6.0.6 on 2026-06-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('found_items', '0002_founditems_category_founditems_created_at_and_more'),
        ('lost_items', '0002_lostitems_category_lostitems_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_answer', models.TextField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('handover_method', models.CharField(blank=True, choices=[('DIRECT', 'Direct Contact'), ('POLICE', 'Police'), ('VENUE', 'Venue Management')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CHALLENGE_PASSED', 'Challenge Passed'), ('OTP_VERIFIED', 'OTP Verified'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='found_items.founditems')),
                ('lost_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='lost_items.lostitems')),
            ],
        ),
    ]
