# Generated by Django 6.0.6 on 2026-07-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0003_remove_lostitems_hidden_details_alter_lostitems_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitems',
            name='dest_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='dest_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='dest_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='location_type',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('ROUTE', 'Route')], default='EXACT', max_length=10),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='source_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='source_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='source_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
