# Generated by Django 6.0.6 on 2026-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0004_lostitems_dest_latitude_lostitems_dest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitems',
            name='description_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='detected_objects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='dominant_colors_detected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='extracted_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='image_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='imei_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='normalized_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='reg_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
