import React from 'react';
import { Sparkles, Search, PlusCircle, ImagePlus, ShieldCheck, EyeOff, Lock, Check } from 'lucide-react';
import { useAppContext } from '../context/AppContext';

export const Home = () => {
  const { navigateTo } = useAppContext();

  return (
    <>
    <div className="section-container">
      <div className="hero-section">
         <div className="hero-badge"><Sparkles size={14} className="text-green" /> AI-Powered Matching</div>
         <h1 className="hero-title">Find what's lost, <br/><span className="text-green">return what's found.</span></h1>
         <p className="hero-desc">The smartest campus lost and found platform. We use AI to match items instantly.</p>
         <div className="hero-buttons">
           <button className="btn-primary" onClick={() => navigateTo('login', null, { regType: 'lost' })}><Search size={18}/> I Lost Something</button>
           <button className="btn-secondary" onClick={() => navigateTo('login', null, { regType: 'found' })}><PlusCircle size={18}/> I Found Something</button>
         </div>
      </div>

      <div className="features-row">
        <div className="feature-item">
          <div className="feature-icon-wrapper icon-green"><ImagePlus size={20} /></div>
          <div className="feature-title">Smart Image AI</div>
          <div className="feature-desc">Upload a photo, we auto-tag and match it.</div>
        </div>
        <div className="feature-item">
          <div className="feature-icon-wrapper icon-purple"><ShieldCheck size={20} /></div>
          <div className="feature-title">Vivar Adar Protocol</div>
          <div className="feature-desc">Secure verification before handovers.</div>
        </div>
      </div>
      <div className="steps-section">
         <h2 className="section-title"><ShieldCheck size={20} style={{display:'inline', verticalAlign: 'middle', marginRight: 8, color: 'var(--primary)'}}/>Secure Verification</h2>
         <p className="section-desc" style={{marginBottom: '0.5rem', fontWeight: 700, color: 'var(--text-dark)'}}>A systematic approach to recovery</p>
         <p className="section-desc">Our methodical process ensures that your items are matched accurately while maintaining complete privacy until verification is confirmed.</p>
         
         <div className="step-card">
           <div className="step-watermark">1</div>
           <div className="step-content">
             <div className="step-icon-box"><Search size={20}/></div>
             <h3 className="step-title">Report Detail</h3>
             <p className="step-text">Submit key details about the item. Avoid specific identifying marks—our AI looks for contextual clues.</p>
           </div>
         </div>
         
         <div className="step-card">
           <div className="step-watermark">2</div>
           <div className="step-content">
             <div className="step-icon-box" style={{color: '#6366F1', backgroundColor: '#EEF2FF', borderColor: '#C7D2FE'}}><Sparkles size={20}/></div>
             <h3 className="step-title">AI Matches</h3>
             <p className="step-text">The system continuously scans reports in your vicinity, highlighting high-probability matches privately.</p>
           </div>
         </div>
         
         <div className="step-card">
           <div className="step-watermark">3</div>
           <div className="step-content">
             <div className="step-icon-box" style={{color: '#047857', backgroundColor: '#D1FAE5', borderColor: '#A7F3D0'}}><ShieldCheck size={20}/></div>
             <h3 className="step-title">Verified Handover</h3>
             <p className="step-text">Answer specific verification questions generated by the AI to confirm ownership before connecting.</p>
           </div>
         </div>
      </div>
    </div>
    
    <div className="privacy-section">
      <div className="privacy-graphic">
        <div className="circle-outer">
          <div className="circle-inner">
            <div className="lock-card">
              <Lock size={32} color="var(--primary)" />
            </div>
          </div>
        </div>
      </div>
      <div className="privacy-badge"><EyeOff size={16}/> Data Minimization</div>
      <h2 className="privacy-title">Your item, your privacy.</h2>
      <p className="privacy-desc">We believe that exposing detailed descriptions of lost items leads to false claims. Our platform acts as a secure intermediary. Details are never shown publicly; they are only used mathematically by our matching algorithms to establish a connection.</p>
      
      <ul className="privacy-list">
        <li className="privacy-list-item"><Check size={16} className="check-icon"/> No public feeds or searchable directories</li>
        <li className="privacy-list-item"><Check size={16} className="check-icon"/> Contact info hidden until verification passes</li>
      </ul>
    </div>
    </>
  );
};
