# Generated by Django 6.0.6 on 2026-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0002_lostitems_category_lostitems_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitems',
            name='hidden_details',
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
