# Generated by Django 6.0.6 on 2026-07-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
