# Generated by Django 6.0.6 on 2026-06-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0003_founditems_handover_type_founditems_wants_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='handover_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='handover_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='handover_place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
