# Generated by Django 6.0.6 on 2026-06-15 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('found_items', '0001_initial'),
        ('lost_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('text_score', models.FloatField()),
                ('image_similarity', models.FloatField()),
                ('match_location', models.FloatField()),
                ('time_score', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STRONG', 'Strong Match'), ('REVIEW', 'Needs Review'), ('DISMISSED', 'Dismissed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='found_items.founditems')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='lost_items.lostitems')),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='VisibilityAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='matching.matchitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'user')},
            },
        ),
    ]
